### PR TITLE
Fixed support for customPaging

### PR DESCRIPTION
**Pull request by sarunas**
Fixed support for customPaging, now it should be used angularjs way:
`<slick custom-paging="ctrl.myCustomPagingFunction(slick, index)" >...</slick>`

cause using it like (sample below) causes just function body inclusion - not execution with right parameters:
`<slick custom-paging="ctrl.myCustomPagingFunction">...</slick>`

### CODE REVIEW

**Comment by nikaspran** [comment]
:+1:

**Comment by donatasdwix** [comment]
+1

**Comment by andriuss** [comment]
:star: +1

**Comment by Boosten** [comment]
+1

**Comment by richardh-vccp** [comment]
+1

**Pull request merged**
