### PR TITLE
Add support to angular 1.4

### PR DESCRIPTION
**Pull request by bertonha**

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by mkramb** [comment]
+1

**Comment by levipadre** [comment]
+1
That would be really great.

**Comment by ddsilva** [comment]
+1

**Comment by michaelperrin** [comment]
+1

**Comment by dirkbartels14050** [comment]
yes, please !

**Comment by bertonha** [comment]
I think this project was DEAD... 7 months without merge/commits :disappointed:

**Comment by razvansandu** [comment]
+1

**Comment by LostCrew** [comment]
+1

**Pull request closed without merging**
